[package]
name = "chiron-horizon-sql"
version = "0.1.6"
edition = "2021"
license = "Apache-2.0"
publish = false

[features]
default = []
duckdb-sidecar = ["chiron-horizon-sql-schema/duckdb-sidecar"]
openapi = ["chiron-horizon-sql-data/openapi", "chiron-horizon-types/openapi"]

[dependencies]
chiron-horizon-sql-core = { path = "../chiron-horizon-sql-core" }
chiron-horizon-sql-data = { path = "../chiron-horizon-sql-data" }
chiron-horizon-sql-dialect = { path = "../chiron-horizon-sql-dialect" }
chiron-horizon-sql-schema = { path = "../chiron-horizon-sql-schema" }
chiron-horizon-types = { path = "../chiron-horizon-types", default-features = false }
